### ISSUE TITLE
Code consistency 

### ISSUE THREAD

**Issue by camilo86** [FRC125/NUPY#5]
We should try to keep our code more consistent, perhaps follow [pep8](https://www.python.org/dev/peps/pep-0008/)? Comes with an awesome script to check where things should be fixed

**Comment by schreiaj** [comment]
I think this is a good idea, why not toss together a quick requirements.txt file that has pep8 and pyfrc in it so we can do a ```pip3 install -r requirements.txt```

**Comment by schreiaj** [comment]
We can also make travisci fail if pep8 doesn't pass with:

```pep8 src```

But first we should probably go through pep8 and see what it defaults to and see if that's what we want.
